/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MyService } from "./components/hylo-nav-bar/hylo-nav-bar";
export namespace Components {
    interface HyloNavBar {
        "isComplete": boolean;
        "myService": MyService;
        "myText": string;
    }
    interface HyloTestCmp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLHyloNavBarElement extends Components.HyloNavBar, HTMLStencilElement {
    }
    var HTMLHyloNavBarElement: {
        prototype: HTMLHyloNavBarElement;
        new (): HTMLHyloNavBarElement;
    };
    interface HTMLHyloTestCmpElement extends Components.HyloTestCmp, HTMLStencilElement {
    }
    var HTMLHyloTestCmpElement: {
        prototype: HTMLHyloTestCmpElement;
        new (): HTMLHyloTestCmpElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "hylo-nav-bar": HTMLHyloNavBarElement;
        "hylo-test-cmp": HTMLHyloTestCmpElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface HyloNavBar {
        "isComplete"?: boolean;
        "myService"?: MyService;
        "myText"?: string;
    }
    interface HyloTestCmp {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "hylo-nav-bar": HyloNavBar;
        "hylo-test-cmp": HyloTestCmp;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hylo-nav-bar": LocalJSX.HyloNavBar & JSXBase.HTMLAttributes<HTMLHyloNavBarElement>;
            "hylo-test-cmp": LocalJSX.HyloTestCmp & JSXBase.HTMLAttributes<HTMLHyloTestCmpElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
